### ISSUE TITLE
Text too large

### ISSUE THREAD

**Issue by Nelarius** [skeletonframework/skeletonframework.github.io#2]
Compared to getskeleton.com, it seems that the text in this version is much larger, especially the title in the landing view.

**Comment by benhinchley** [comment]
This seems to be personal preference, and not really an issue. Though in terms of the text being too large, The only typographical changes we have made, have been incredibly small if any from memory @gld1982ltd correct me if i'm wrong. 

The base font size has changed from the 62.5% font size hack used in [dhg/skeleton](https://github.com/dhg/Skeleton), to 1em aka 16px.

**Comment by Nelarius** [comment]
Yeah, I guess I was just nitpicking about the fact that on the landing page, the three icons are no longer centered height-wise, but are much closer to the bottom of the page instead.

**Comment by benhinchley** [comment]
That would be due to this rule

```css
@media (min-width: 550px) {
  .header {
      margin-top: 18rem;
  }
}
```

**Comment by gld1982ltd** [comment]
FIxed

```css
.header {
  margin-top: 4rem;
  text-align: center; }
```
